package gui;

import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;

import core.Attribute;
import core.AttributeRating;

import client.ClientAttribute;
/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * GUIAddNewAttribute.java
 *
 * Created on Dec 8, 2011, 3:49:06 PM
 */
/**
 *
 * @author Russell Mull
 */
public class GUIAddNewAttribute extends javax.swing.JFrame {

    /** Creates new form GUIAddNewAttribute */
    public GUIAddNewAttribute() 
    {
        initComponents();
        
        setDefaultCloseOperation(DISPOSE_ON_CLOSE);
        setSize(250, 150);
        setVisible(true);
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        addAttributeButton = new javax.swing.JButton();
        attributeLabel = new javax.swing.JLabel();
        attributeTextField = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        addAttributeButton.setText("Add Attribute");
        addAttributeButton.addActionListener(new ActionListener()
        {
        	public void actionPerformed(ActionEvent e)
        	{
        		ClientAttribute newAtt = new ClientAttribute(attributeTextField.getText());
        		
        		DataAbstraction.getInstance().getUser().setAttributeRating(newAtt.getAttributeId(), 0);
        		
        		DataAbstraction.getInstance().getMainPane().myAttributes.populateAttributes();
        	}
        });

        attributeLabel.setText("Attribute:");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(26, 26, 26)
                        .addComponent(attributeLabel)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(attributeTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 126, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(65, 65, 65)
                        .addComponent(addAttributeButton)))
                .addContainerGap(21, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(attributeLabel)
                    .addComponent(attributeTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(addAttributeButton)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton addAttributeButton;
    private javax.swing.JLabel attributeLabel;
    private javax.swing.JTextField attributeTextField;
    // End of variables declaration//GEN-END:variables
}
