package gui;

import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.util.List;
import java.util.Vector;

import javax.swing.JOptionPane;

import client.ClientConsumable;
import client.ClientRecommendation;
import client.ClientUser;
/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

import core.AttributeRating;
import core.Consumable;
import core.Rating;
import core.Recommendation;

/*
 * GUISearch.java
 *
 * Created on Nov 29, 2011, 3:24:19 PM
 */
/**
 *
 * @author Russell Mull
 */
public class GUISearch extends javax.swing.JPanel {

	private List<Consumable> consumablesFromSearch;
	private List<Recommendation> allRecommendations;
	private final Vector<String> resultsAsStrings  = new Vector<String>();;
	
	
    /** Creates new form GUISearch */
    public GUISearch() 
    {
        initComponents();
    }
    
    //********************************************
    public List<Consumable> search(String searchPhrase)
    {
    	ClientConsumable c = new ClientConsumable(1);	
    	return c.search(searchPhrase);
    }
    
    public Vector<String> getSearchResults()
    {
    	Vector<String> retVec = new Vector<String>();
    	
    	return retVec;
    }
    //********************************************

    public void updateSearch()
    {
    	String searchPhrase = searchTextField.getText();
    	
    	if(searchPhrase == null || searchTextField.getText().equals(""))
    	{
    		return;
    	}
    	
    	consumablesFromSearch = search(searchPhrase);

    	resultsAsStrings.removeAllElements();
		for(Consumable c : consumablesFromSearch)
		{
			resultsAsStrings.add(c.getName());
		}
		
		populateResults();
    }
    
    public void populateResults()
    {
    	resultsList.setModel(new javax.swing.AbstractListModel() {
        	Vector<String> strings = resultsAsStrings;
        	public int getSize() { return strings.size(); }
        	public Object getElementAt(int i) { return strings.get(i); }
        });
    }
    
    public void updateAllRecommendations()
    {
    	allRecommendations = DataAbstraction.getInstance().getUser().getRatedConsumables();
    }
    //********************************************

    
    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
    	
        searchTextField = new javax.swing.JTextField();
        searchButton = new javax.swing.JButton();
        ratingSlider = new javax.swing.JSlider();
        setRatingButton = new javax.swing.JButton();
        ratingLabel = new javax.swing.JLabel();
        listScrollPane = new javax.swing.JScrollPane();
        resultsList = new javax.swing.JList();
        addToConsumablesButton = new javax.swing.JButton();

        setPreferredSize(new java.awt.Dimension(400, 300));

        
        /*
         * loginButton.addActionListener(new ActionListener() {
            public void actionPerformed(ActionEvent evt) 
            {
                login(false);
                JOptionPane.showMessageDialog(null, "Login Successful");
            }
        });
         */
        
        searchButton.setText("Search");
        searchButton.addActionListener(new ActionListener()
        {
        	public void actionPerformed(ActionEvent e)
        	{
        		if(e.getSource() == searchButton)
        		{
        			updateSearch();
        		}
        	}
        });
        

        ratingSlider.setMajorTickSpacing(1);
        ratingSlider.setMaximum(5);
        ratingSlider.setPaintLabels(true);
        ratingSlider.setPaintTicks(true);
        ratingSlider.setSnapToTicks(true);

        
        setRatingButton.setText("Set Rating");
        setRatingButton.addActionListener(new ActionListener() {
			public void actionPerformed(ActionEvent e) {
				if(e.getSource() == setRatingButton)
				{
					int rating = ratingSlider.getValue();
					System.out.println(rating);
					
					
					ClientConsumable c = (ClientConsumable) consumablesFromSearch.get(resultsList.getSelectedIndex());
					
					System.out.println(c.getName());
					
					Recommendation r = new ClientRecommendation(DataAbstraction.getInstance().getUser(), c, rating);
					//r.setRevisedRating(rating);
					
					//Reload the consumables list.
					DataAbstraction.getInstance().getMainPane().myConsumables.populateConsumables();
					
					//Reload our recommendations list
					//allRecommendations.remove(r);
					//allRecommendations.add(r);
					//allRecommendations = DataAbstraction.getInstance().getUser().getRatedConsumables();
					//updateSearch();
					updateAllRecommendations();
				}
			}	
        });
        

        ratingLabel.setText("Rating:");

        listScrollPane.setVerticalScrollBarPolicy(javax.swing.ScrollPaneConstants.VERTICAL_SCROLLBAR_ALWAYS);

        resultsList.setModel(new javax.swing.AbstractListModel() {
            Vector<String> strings = getSearchResults();
            public int getSize() { return strings.size(); }
            public Object getElementAt(int i) { return strings.get(i); }
        });
        resultsList.addListSelectionListener(new javax.swing.event.ListSelectionListener() {
            public void valueChanged(javax.swing.event.ListSelectionEvent evt) {
            	if(evt.getSource() == resultsList)
            		resultsListValueChanged(evt);
            }
        });
        listScrollPane.setViewportView(resultsList);

        addToConsumablesButton.setText("Add New Consumables");
        addToConsumablesButton.addActionListener(new ActionListener()
        {
			public void actionPerformed(ActionEvent e) 
			{
				GUIAddNewConsumable consum = new GUIAddNewConsumable();
			}
        });
        
        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(searchTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 149, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(searchButton))
                    .addComponent(listScrollPane, javax.swing.GroupLayout.PREFERRED_SIZE, 139, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(addToConsumablesButton))
                .addContainerGap(152, Short.MAX_VALUE))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(172, 172, 172)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(ratingSlider, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(ratingLabel))
                        .addComponent(setRatingButton))
                    .addContainerGap(28, Short.MAX_VALUE)))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(40, 40, 40)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(searchTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(searchButton))
                .addGap(18, 18, 18)
                .addComponent(listScrollPane, javax.swing.GroupLayout.PREFERRED_SIZE, 158, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(addToConsumablesButton)
                .addGap(41, 41, 41))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(109, 109, 109)
                    .addComponent(ratingLabel)
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                    .addComponent(ratingSlider, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                    .addComponent(setRatingButton)
                    .addContainerGap(97, Short.MAX_VALUE)))
        );
    }// </editor-fold>//GEN-END:initComponents


private void resultsListValueChanged(javax.swing.event.ListSelectionEvent evt) {//GEN-FIRST:event_resultsListValueChanged
	if(evt.getSource() == this.resultsList && resultsList.getSelectedIndex() != -1)
	{
		Consumable selected = consumablesFromSearch.get(resultsList.getSelectedIndex());
		
		
		
		if(allRecommendations == null &&  DataAbstraction.getInstance() != null && DataAbstraction.getInstance().getUser() != null)
		{
			allRecommendations = DataAbstraction.getInstance().getUser().getRatedConsumables();
		}
		
		//Check to see if the recommendation exists. If it does, use the revised rating. if it does not, use an initial rating. 
		for(Recommendation r : allRecommendations)
		{
			if(r.getConsumable().getConsumableId() == selected.getConsumableId())
			{
				System.out.println("hjere" + selected.getName());
				ratingSlider.setValue(r.getRevisedRating());
				return;
			}
		}
		
		Rating r = new Rating(DataAbstraction.getInstance().getUser(), selected);
		ratingSlider.setValue(r.getInitialRating());
	}
}//GEN-LAST:event_resultsListValueChanged








	// Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton addToConsumablesButton;
    private javax.swing.JScrollPane listScrollPane;
    private javax.swing.JLabel ratingLabel;
    private javax.swing.JSlider ratingSlider;
    private javax.swing.JList resultsList;
    private javax.swing.JButton searchButton;
    private javax.swing.JTextField searchTextField;
    private javax.swing.JButton setRatingButton;
    // End of variables declaration//GEN-END:variables
}
